language: python
matrix:
  include:
  - name: "3.7.2 Unittest"
    python: "3.7-dev"
    env: TEST_SUITE=UNITTEST
         APPLICATION_ENV=Testing
         SQLALCHEMY_DATABASE_URI=postgresql://postgres:@localhost/challenge        

install:
  - pip install -r requirements-dev.txt

services:
 - postgresql

addons:
  postgresql: 9.6

before_script:
 - psql --version
 - psql -U postgres -c 'create database challenge;'

branches:
  only:
  - master

script: 
  - python manager.py create 
  - make tests
