language: python
matrix:
  include:
  - name: "3.7.2 Unittest"
    python: "3.7-dev"
    env: TEST_SUITE=UNITTEST
         APPLICATION_ENV=Testing
         SQLALCHEMY_DATABASE_URI=postgresql://postgres:@localhost/challenge        

install:
  - pip install -r requirements-dev.txt

services:
  postgres:
    adapter: postgresql
    database: challenge
    username: postgres
  addons:
    postgresql: 9.6

  before_script:
    - "psql -c 'create database challenge;' -U postgres"
    - "rake db:migrate"
branches:
  only:
  - master

script: python manager.py create && make tests
