language: python
matrix:
  include:
  - name: "3.7.2 Unittest"
    python: "3.7-dev"
    env: TEST_SUITE=UNITTEST
         APPLICATION_ENV=Testing
         SQLALCHEMY_DATABASE_URI=postgresql://postgres:123456@localhost/challenge        

install:
  - pip install -r requirements-dev.txt

services:
  addons:
    postgresql: 9.6

  before_script:
    - psql -c 'create database challenge;' -U postgres
    - psql -c "CREATE USER admin WITH PASSWORD '123456';" -U postgres
branches:
  only:
  - master

script: python manager.py create && make tests
